#ifndef _DEBUG_CONFIG_H_
#define _DEBUG_CONFIG_H_

#define DEBUG_EEPROM
#define DEBUG_TRIGGER_STATE 
#define DEBUG_REEL_SELECTION
//#define DEBUG_ULTRASONIC
#define DEBUG_DETECTORS
#define DEBUG_MOTORS
//#define DEBUG_FLASH_MOTOR_NUMBER_ON_LED

//#define ECHO_SERIAL_INPUT

#endif
